### ISSUE TITLE
panic when editing a "zitadel_org_member"

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/terraform-provider-zitadel#19]
After having successfully created this resource:
```tf
resource "zitadel_org_member" "org_admin_member" {
  depends_on = [zitadel_org.main_org, zitadel_machine_user.admin_user]

  org_id  = zitadel_org.main_org.id
  user_id = zitadel_machine_user.admin_user.id

  roles = ["ORG_USER_MANAGER"]
}
```

I tried editing the `roles` as such:
```tf
resource "zitadel_org_member" "org_admin_member" {
  depends_on = [zitadel_org.main_org, zitadel_machine_user.admin_user]

  org_id  = zitadel_org.main_org.id
  user_id = zitadel_machine_user.admin_user.id

  roles = ["IAM_ORG_MANAGER"]
}
```

planning works, but I get a panic when applying:
```
╷
│ Error: Request cancelled
│ 
│   with module.cloud.module.main_configuration.zitadel_org_member.org_admin_member,
│   on main_configuration/main.tf line 79, in resource "zitadel_org_member" "org_admin_member":
│   79: resource "zitadel_org_member" "org_admin_member" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-zitadel_v1.0.0-alpha.8 plugin:

panic: interface conversion: interface {} is *schema.Set, not []string

goroutine 87 [running]:
github.com/zitadel/terraform-provider-zitadel/zitadel/v2/org_member.update({0x1bb61a8, 0xc0000a7860}, 0x18d48c0?, {0x186cec0?, 0xc0002dae80})
        github.com/zitadel/terraform-provider-zitadel/zitadel/v2/org_member/funcs.go:53 +0x397
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc00014dce0, {0x1bb61e0, 0xc000873800}, 0xd?, {0x186cec0, 0xc0002dae80})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:741 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00014dce0, {0x1bb61e0, 0xc000873800}, 0xc0002a3c70, 0xc000986280, {0x186cec0, 0xc0002dae80})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000293d70, {0x1bb6138?, 0xc0002db9c0?}, 0xc00086ab40)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000256460, {0x1bb61e0?, 0xc000873020?}, 0xc0008663f0)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1a135e0?, 0xc000256460}, {0x1bb61e0, 0xc000873020}, 0xc000866380, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002a4000, {0x1bb9b58, 0xc0003d16c0}, 0xc000869440, 0xc0000b3c80, 0x2282740, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb2b
google.golang.org/grpc.(*Server).handleStream(0xc0002a4000, {0x1bb9b58, 0xc0003d16c0}, 0xc000869440, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-zitadel_v1.0.0-alpha.8 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

ZITADEL version: 2.3.3

**Comment by stebenz** [comment]
Changed in v1.0.0-alpha.9, if not please reopen issue
